CHANGELOG_GOOGLE_SIGNON.md
FIREBASE_SETUP_INSTRUCTIONS.md
backend/env.example
backend/package-lock.json
backend/package.json
backend/src/routes/googleMobileAuth.js
backend/src/server.js
backend/src/utils/firebaseAdmin.js
backend/tests/googleAuth.mobile.test.js
backend/tests/setup.js
mobile/android/app/build.gradle
mobile/android/app/desktop.ini
mobile/android/app/google-services.json
mobile/android/app/src/main/AndroidManifest.xml
mobile/android/app/src/main/java/com/foci/mobile/MainActivity.kt
mobile/android/app/src/main/java/com/foci/mobile/MainApplication.kt
mobile/android/build.gradle
mobile/package-lock.json
mobile/package.json
mobile/react-native.config.js
mobile/src/__tests__/GoogleAuth.integration.test.tsx
mobile/src/components/common/AccountLinkingModal.tsx
mobile/src/components/common/GoogleSignInButton.tsx
mobile/src/components/common/index.ts
mobile/src/screens/auth/LoginScreen.tsx
mobile/src/screens/auth/SignupScreen.tsx
mobile/src/services/auth.ts
mobile/src/services/config.ts
mobile/src/services/googleAuth.ts
